/************************************************
BSD 3-Clause License

Copyright (c) 2019, HPCN Group, UAM Spain (hpcn-uam.es)
and Systems Group, ETH Zurich (systems.ethz.ch)
All rights reserved.


Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

************************************************/

#define XIPERF2_CLIENT_SETTINGS_BASE_ADDRESS               0x5000

#define XIPERF2_CLIENT_SETTINGS_ADDR_RUNEXPERIMENT_V_DATA  0x10
#define XIPERF2_CLIENT_SETTINGS_BITS_RUNEXPERIMENT_V_DATA  1
#define XIPERF2_CLIENT_SETTINGS_ADDR_DUALMODEEN_V_DATA     0x18
#define XIPERF2_CLIENT_SETTINGS_BITS_DUALMODEEN_V_DATA     1
#define XIPERF2_CLIENT_SETTINGS_ADDR_USETIMER_V_DATA       0x20
#define XIPERF2_CLIENT_SETTINGS_BITS_USETIMER_V_DATA       1
#define XIPERF2_CLIENT_SETTINGS_ADDR_RUNTIME_V_DATA        0x28
#define XIPERF2_CLIENT_SETTINGS_BITS_RUNTIME_V_DATA        64
#define XIPERF2_CLIENT_SETTINGS_ADDR_NUMCONNECTIONS_V_DATA 0x34
#define XIPERF2_CLIENT_SETTINGS_BITS_NUMCONNECTIONS_V_DATA 14
#define XIPERF2_CLIENT_SETTINGS_ADDR_TRANSFER_SIZE_V_DATA  0x3c
#define XIPERF2_CLIENT_SETTINGS_BITS_TRANSFER_SIZE_V_DATA  32
#define XIPERF2_CLIENT_SETTINGS_ADDR_PACKET_MSS_V_DATA     0x44
#define XIPERF2_CLIENT_SETTINGS_BITS_PACKET_MSS_V_DATA     12
#define XIPERF2_CLIENT_SETTINGS_ADDR_IPDESTINATION_V_DATA  0x4c
#define XIPERF2_CLIENT_SETTINGS_BITS_IPDESTINATION_V_DATA  32
#define XIPERF2_CLIENT_SETTINGS_ADDR_DSTPORT_V_DATA        0x54
#define XIPERF2_CLIENT_SETTINGS_BITS_DSTPORT_V_DATA        16
#define XIPERF2_CLIENT_SETTINGS_ADDR_MAXCONNECTIONS_V_DATA 0x5c
#define XIPERF2_CLIENT_SETTINGS_BITS_MAXCONNECTIONS_V_DATA 16
#define XIPERF2_CLIENT_SETTINGS_ADDR_MAXCONNECTIONS_V_CTRL 0x60